apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-http-app-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-http-app-b
  template:
    metadata:
      labels:
        app: sample-http-app-b
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - name: http-port
          containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: "/etc/nginx"
          readOnly: true
        - name: html-path-app3
          mountPath: "/usr/share/nginx/html/app3"
          readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            # マウントしたいConfigMapの名前を指定します。
            name: html-path-b
            # ファイルとして作成するConfigMapのキーの配列
            items:
            - key: "nginx.conf"
              path: "nginx.conf"
        # Podレベルでボリュームを設定し、Pod内のコンテナにマウントします。
        - name: html-path-app3
          configMap:
            # マウントしたいConfigMapの名前を指定します。
            name: html-path-b
            # ファイルとして作成するConfigMapのキーの配列
            items:
            - key: "app3"
              path: "index.html"
            