apiVersion: v1
kind: Service
metadata:
  name: http-service-a
  labels:
    app: sample-http-app-a
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http-port
  selector:
    app: sample-http-app-a